kuoss/helm-charts

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/venti/cm-dashboards.yaml
- charts/venti-stack/templates/venti/deploy.yaml
- charts/venti-stack/values.yaml
> 0.1.12 - venti:v0.2.3 eventrouter systemd

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/lethe/deploy.yaml
> Update Chart version 0.1.13

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/venti/deploy.yaml
> chart-0.1.14

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/venti/deploy.yaml
> Update Chart.yaml - venti-stack-0.1.15

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/venti/deploy.yaml
> venti-stack-0.1.17

- charts/code-server-go/Chart.yaml
- charts/code-server-go/templates/ingress.yaml
- charts/code-server-go/values.yaml
> code-server-go:v0.0.3

- charts/code-server-go/Chart.yaml
- charts/code-server-go/templates/service.yaml
- charts/code-server-go/values.yaml
> code-server-go:0.0.4

- charts/code-server-go/Chart.yaml
- charts/code-server-go/values.yaml
> code-server-go-0.0.5

- charts/code-server-go/Chart.yaml
code-server-go:v4.17.0-go1.12.1 (chart 0.0.6)
- fixes #13
> code-server-go:v4.17.0-go1.12.1 (chart 0.0.6)

- charts/code-server-go/Chart.yaml
- charts/code-server-go/values.yaml
[code-server-go] remove image tag
- fixes #15 
none
> [code-server-go] remove image tag

- charts/code-server-go/Chart.yaml
- charts/code-server-go/templates/extra-manifests.yaml
- charts/code-server-go/templates/service.yaml
- charts/code-server-go/values.yaml
[code-server-go] extra ports
- fixes #17
> [code-server-go] extra ports

- charts/code-server-go/Chart.yaml
- charts/code-server-go/templates/deploy.yaml
- charts/code-server-go/templates/pvc.yaml
- charts/code-server-go/values.yaml
[code-server-go] add pvc
- fixes #19 
Thank you
> [code-server-go] add pvc

- charts/code-server-go/Chart.yaml
code-server-go v4.17.0-go1.12.1-p1
- fixes #21 
thx
> code-server-go v4.17.0-go1.12.1-p1

- .github/workflows/lint-test.yaml
- charts/venti-stack/Chart.yaml
> venti v0.2.18

- Makefile
- charts/venti-stack/Chart.lock
- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/eventrouter/deploy.yaml
- charts/venti-stack/templates/lethe/deploy.yaml
bump for security
- fixes #34 
Thanks
> [venti-stack] bump for security

- charts/code-server-go/Chart.yaml
- charts/code-server-go/templates/deploy.yaml
- charts/code-server-go/values.yaml
We can set serviceAccountName.
- fixes #38
> [code-server-go] add serviceAccountName

- README.md
- charts/venti-stack/Chart.lock
- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/NOTES.txt
- A better way to check
- Add link to chart readme
- fixes #36 
Thank you
> 36 venti-stack-0.1.34

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/lethe/deploy.yaml
[venti-stack] bump fluent-bit 2.2.2
- fixes #44
> [venti-stack] bump fluent-bit 2.2.2

- hack/diff_fluentbit.sh
- hack/diff_prometheus.sh
[venti-stack] diff-subcharts
- fixes #46
> [venti-stack] diff-subcharts

- charts/venti-stack/Chart.yaml
> venti v0.2.20

- charts/myip/Chart.yaml
> [myip] 0.1.4 (app v0.1.3)

- charts/myip/Chart.yaml
- charts/myip/Makefile
- charts/myip/values.schema.json
> [myip] values schema

- charts/myip/Chart.yaml
> [myip] signed

- .github/workflows/release.yml
> signed chart

- charts/myip/Chart.yaml
> [myip] bump for signed

- .github/workflows/release.yml
> workflow-release

- .github/workflows/lint-test.yaml
- .github/workflows/release.yml
- charts/venti-stack/Chart.lock
- charts/venti-stack/Chart.yaml
- docs/venti-stack.rendered.test.yaml
> [venti-stack] CVE-2024-4323

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/lethe/deploy.yaml
lethe fluent-bit 3.0.4
fixes:
- #67 
- #69
> [venti-stack] fluent-bit CVE-2024-4323 v2

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/lethe/pvc.yaml
- charts/venti-stack/values.yaml
- docs/venti-stack.rendered.test.yaml
lethe pvc storageclass
- fixes #71 
```console
$ helm template vs . | grep storageClass
$ helm template vs . --set lethe.persistentVolume.storageClass="aaa" | grep storageClass
storageClassName: "aaa"
```
> lethe pvc storageclass

- charts/code-server-go/Chart.yaml
> deprecate code-server-go chart

- charts/ingress-annotator/Chart.yaml
- charts/ingress-annotator/README.md
> [ingress-annotator] README.md

- charts/ingress-annotator/Chart.yaml
- charts/ingress-annotator/README.md
> [ingress-annotator] Chart.yaml

- charts/ingress-annotator/Chart.yaml
- charts/ingress-annotator/templates/role.yaml
> [ingress-annotator] leader-election-role

- charts/ingress-annotator/Chart.yaml
- charts/ingress-annotator/README.md
- charts/ingress-annotator/templates/configmap.yaml
- charts/ingress-annotator/templates/role.yaml
- charts/ingress-annotator/values.yaml
> ingress-annotator v0.1.7

- charts/ingress-annotator/Chart.yaml
- charts/ingress-annotator/values.schema.json
> 90 ingress annotator values schema

- .github/workflows/lint-test.yaml
- .github/workflows/release.yml
- charts/ingress-annotator/Chart.yaml
- charts/ingress-annotator/README.md
- charts/ingress-annotator/templates/NOTES.txt
- charts/ingress-annotator/templates/deployment.yaml
> [ingress-annotator] app v0.1.8

- charts/ingress-annotator/Chart.yaml
> [ingress-annotator] app v0.1.10

- charts/ingress-annotator/Chart.yaml
> [ingress-annotator] app v0.1.11

- charts/venti-stack/Chart.yaml
- charts/venti-stack/values.schema.json
- hack/venti-stack_values_schema/create.sh
- hack/venti-stack_values_schema/fluent-bit.values.schema.json
- hack/venti-stack_values_schema/prometheus.values.schema.json
- hack/venti-stack_values_schema/venti-stack.base.values.schema.json
> venti-stack values schema

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/NOTES.txt
- charts/venti-stack/templates/eventrouter/clusterrole.yaml
- charts/venti-stack/templates/eventrouter/clusterrolebinding.yaml
- charts/venti-stack/templates/eventrouter/cm.yaml
- charts/venti-stack/templates/eventrouter/deploy.yaml
- charts/venti-stack/templates/eventrouter/serviceaccount.yaml
- charts/venti-stack/values.schema.json
- charts/venti-stack/values.yaml
> [venti-stack] Add eventrouter enabled

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/venti/clusterrole.yaml
- charts/venti-stack/templates/venti/clusterrolebinding.yaml
- charts/venti-stack/templates/venti/cm-alertrules.yaml
- charts/venti-stack/templates/venti/cm-dashboards.yaml
- charts/venti-stack/templates/venti/cm.yaml
- charts/venti-stack/templates/venti/deploy.yaml
- charts/venti-stack/templates/venti/ingress.yaml
- charts/venti-stack/templates/venti/service.yaml
- charts/venti-stack/templates/venti/serviceaccount.yaml
- charts/venti-stack/values.schema.json
- charts/venti-stack/values.yaml
> 108 venti stack ventienabled

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/venti/cm-dashboards.yaml
> [venti-stack] node root fs%

- charts/venti-stack/Chart.yaml
- charts/venti-stack/values.schema.json
- charts/venti-stack/values.yaml
> [venti-stack] prometheus enabled true

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/venti/cm.yaml
> [venti-stack] remove .Values.prometheus.server.enabled

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/NOTES.txt
> [venti-stack] NOTES.txt timeout

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/venti/cm.yaml
- charts/venti-stack/values.schema.json
- charts/venti-stack/values.yaml
> [venti-stack] Add chart label in alert globalLabels

- charts/venti-stack/Chart.lock
- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/eventrouter/deploy.yaml
- charts/venti-stack/templates/lethe/deploy.yaml
[venti-stack] bump 2024-11
- fixes #121
> [venti-stack] bump 2024-11

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/lethe/deploy.yaml
> [venti-stack] fluent-bit:3.1.9

- charts/venti-stack/Chart.yaml
> [venti-stack] venti:v0.2.22

- Makefile
- charts/venti-stack/Chart.lock
- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/lethe/deploy.yaml
> [venti-stack] 0.2.15

- charts/venti-stack/Chart.yaml
- charts/venti-stack/values.yaml
> [venti-stack] remove kubernetes filter

- charts/venti-stack/Chart.yaml
- charts/venti-stack/values.yaml
> [venti-stack] lethe:v0.2.11

- .github/workflows/lint-test.yaml
- Makefile
- charts/venti-stack/Chart.yaml
- hack/check_image_tags.py
- hack/checks.sh
> [venti-stack] checks image tags

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/eventrouter/deploy.yaml
> [venti-stack] eventrouter:v0.4.7

- .github/workflows/lint-test.yaml
- charts/ingress-annotator/Chart.yaml
- charts/ingress-annotator/templates/NOTES.txt
- charts/ingress-annotator/templates/configmap.yaml
- charts/ingress-annotator/values.schema.json
- charts/ingress-annotator/values.yaml
> [ingress-annotator] appVersion: v0.2.2

- charts/myip/Chart.yaml
- charts/myip/values.yaml
> [myip] appVersion v0.1.6

- .github/workflows/lint-test.yaml
- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/eventrouter/deploy.yaml
[venti-stack] Bump eventrouter from v0.4.10 to v0.4.11
- fixes #146
> [venti-stack] Bump eventrouter from v0.4.10 to v0.4.11

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/eventrouter/deploy.yaml
- charts/venti-stack/values.yaml
> [venti-stack] eventrouter resources

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/venti/cm-alertrules.yaml
- hack/check_image_tags.py
- hack/checks.sh
> alert rules enabled

- charts/venti-stack/Chart.yaml
- charts/venti-stack/values.yaml
> [venti-stack] vcustom summaries

- charts/myip/Chart.yaml
- charts/myip/templates/service.yaml
- charts/myip/values.yaml
> [myip] appVersion v0.1.7

- charts/venti-stack/Chart.yaml
- charts/venti-stack/templates/_helpers.tpl
- charts/venti-stack/templates/lethe/deploy.yaml
- charts/venti-stack/templates/lethe/serviceaccount.yaml
- charts/venti-stack/values.schema.json
- charts/venti-stack/values.yaml
> [venti-stack] lethe service account

- charts/venti-stack/Chart.yaml
- charts/venti-stack/values.yaml
> [venti-stack] alert summary
